# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:

- script: 'git config --global user.name "teams.trifenix"'
  displayName: 'git config --global user.name '

- script: 'git config --global user.email "teams.trifenix@trifenix.io"'
  displayName: 'git config --global user.name '

- script: 'git remote add githubEjemplo "https://trifenix:7075e1dbe014ad2833c63d62fbefe9d68efd9a3a@github.com/trifenix/ejemplo1.git"'
  displayName: 'git remote add '

- script: 'git checkout master'
  displayName: 'git checkout master '

# - script: 'git checkout -b masterEjemplo'
#   displayName: 'git checkout masterEjemplo '

# - script: 'git branch'
#   displayName: 'git branch '

# - script: 'git pull githubEjemplo master'
#   displayName: 'git pull githubEjemplo master '

- script: 'git push githubEjemplo master'
  displayName: 'git push -u githubEjemplo master '  