pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - master

steps:
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'drop'
      publishLocation: 'container'
  #fin publicando artifacts

