# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:

- script: 'git remote add githubEjemplo " https://trifenix:7075e1dbe014ad2833c63d62fbefe9d68efd9a3a@github.com/trifenix/ejemplo.git"'
  displayName: 'git remote add '

- script: |
   git remote -v
   git status
   git log --oneline
   git pull githubEjemplo master
   git push githubEjemplo master
   
  displayName: 'push to githubEjemplo'
