# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:

- script: 'git config --global user.name "Murray-Trifenix"'
  displayName: 'git config --global user.name '

- script: 'git config --global user.email "sebastian.murray@trifenix.com"'
  displayName: 'git config --global uuser.email '

- script: 'git remote add githubEjemplo "https://trifenix:7075e1dbe014ad2833c63d62fbefe9d68efd9a3a@github.com/trifenix/ejemplo1.git"'
  displayName: 'git remote add '

- script: 'git checkout master'
  displayName: 'git checkout master '

- script: 'git branch --set-upstream-to master githubEjemplo/master'
  displayName: 'git master set upstream ' 

# - script: 'git branch'
#   displayName: 'git branch '

# - script: 'git log --oneline'
#   displayName: 'show '

# - script: 'git pull githubEjemplo master'
#   displayName: 'git pull githubEjemplo master '

- script: 'git push "https://trifenix:7075e1dbe014ad2833c63d62fbefe9d68efd9a3a@github.com/trifenix/ejemplo1.git" master'
  displayName: 'git push -u githubEjemplo master '  